### PR TITLE
Only show run command with fix message if command was run without it

### LINKED ISSUE #60: Only print "--fix to automatically fix some problems." when some problems are fixable
We currently print  `standard: Run `standardrb --fix` to automatically fix some problems.` unnecessarily. Stop printing it when:

- [x] `--fix` was used in the run (fixed by #69)
- [ ] none of the detected problems were (safely) autofixable

Code is in the lib/standard/formatter.rb

### PR DESCRIPTION
**Pull request by chadmmills**
Fixes #60 

I believe this handles the first task on the issue. I'm not sure if there is something extra I need to check for handling the second task - `Stop printing it when ... none of the detected problems were (safely) autofixable`

### CODE REVIEW

File: lib/standard/formatter.rb [hunk 1]
```diff
@@ -42,14 +42,24 @@ def print_header_once
...
       @header_printed_already = true
     end
 
     def print_call_for_feedback
       output.print "\n"
       output.print CALL_TO_ACTION_MESSAGE
     end
+
+    def auto_correct_option_provided?
+      options[:auto_correct] || options[:safe_auto_correct]
```
Comment (chadmmills) [inline lib/standard/formatter.rb]: Wasn't sure if I needed to check for both options here?

Comment (searls) [reply lib/standard/formatter.rb]: Seems reasonable

**Comment by searls** [comment]
Thanks for this. Gonna reopen the issue and leave the other task open
